### ISSUE TITLE
Forbidden by KEGG?

### ISSUE THREAD

**Issue by grittyy** [mentatpsi/KEGG-Crawler#1]
Hi there,

When using this crawler, do you experience access forbidden by KEGG? Since there will be to many data retrieval requests sent from the same IP.

Thanks,
G

**Comment by mentatpsi** [comment]
I haven't noticed any issue of that nature. It continues a crawl request several times before giving up, and they crawl attempts last for about 30 seconds each, so it gives it enough time. Are you seeing anything of that nature? Can you give me a little bit more detail as well?

Regards,
Shay

**Comment by grittyy** [comment]
I am just curious. Since it tries a crawl several times and last for 30 seconds, that should not be a problem. I have a script of my own to crawl all genes to reactions pairs for one genome, which requires thousands of crawls queued into 8 threads. After trying several genomes, KEGG blocked my access. When I stopped crawling, I regain the access to KEGG. I thought you might have met similar situation. I should try your code and see if I have the same thing.

Thanks a lot!
G

**Comment by mentatpsi** [comment]
Funny, we both seemed to approach it similarly. I also have 8 threads that perform thousands of crawls using queues. What I can state is, this script develops pickle files that contain genetic data as well. It is quite possible to remodel the code, or just incorporate the pickle files (one of which is 80 MBs) to transform the data based on your necessity. I find this optimal as it's quite possible that a genome based crawl might revisit old pairings unless caching is utilized, although I might have merely misunderstood what you meant. This method should examine each point only once. Your project endeavor sounds pretty interesting. 

It's been awhile since i've worked on this code, but I can provide some recommendations regarding remodeling the pickle files or transforming the read in in a way that provides what you need.

Regards,
Shay

**Comment by mentatpsi** [comment]
Closing since 4 years old
